# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24ad64cfc81803a0c8cbf741052b894031d026c8cca582ef3a816a433f0db63d5bd5422e6834790a391542631b200ac579f0474506acaebfe37414b1dc19c19f

test:
  secret_key_base: 243b5f1e6bb3fea1642a93e3486837414aaacb1ea427a8f6079612e21437cecf5439d284afaee2cc1f823d173f1ced45cd71bf589f94181db74ae13617809879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
